# Generated by Django 3.1.6 on 2021-02-19 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0004_auto_20210219_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='mp4',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
